backend:
  name: git-gateway
  branch: dev

local_backend: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: projects
    label: Projects
    label_singular: Project
    description: >
      All creative, visual-effects and coding projects shown on the portfolio page.
    folder: content/projects
    create: true
    fields:
      - label: Project Title
        name: title
        widget: string
        hint: The project title.
      - label: Project Year
        name: year
        widget: number
        default: 2021
        value_type: int
        min: 2017
        hint: The year this project was made/finished.
      - label: Project Thumbnail
        name: thumbnail
        widget: image
        hint: A thumbnail used for the card on the overview portfolio page.
        media_library:
          allow_multiple: false
      - label: Description
        name: body
        widget: markdown
        hint: A short description about the project.
      - label: Github Link
        name: gh_link
        widget: string
        hint: A link to the github page if there is one.
      - label: Project Link
        name: pr_link
        widget: string
        hint: A link to a video or project page if there is one.